# -*- coding: utf-8 -*-
"""synthetic sales data.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12pPLD_0OQG_96as_Osx9DzfT8Rzcnkn2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ==============================
# 2. Generate Synthetic Dataset
# ==============================
np.random.seed(42)

# Create months for 2 years (24 months)
months = pd.date_range(start='2023-01-01', periods=24, freq='M')

regions = ['North', 'South', 'East', 'West']

data = {
    'Month': np.tile(months, 4),
    'Region': np.repeat(regions, 24),
    'Units_Sold': np.random.randint(50, 300, 96),
    'Revenue': np.random.randint(5000, 30000, 96)
}

df = pd.DataFrame(data)

print("First 5 Rows of Dataset:")
print(df.head())

# ==============================
# 3. Data Cleaning & Preparation
# ==============================
print("\nData Types:")
print(df.dtypes)

# Ensure Month is datetime
df['Month'] = pd.to_datetime(df['Month'])

# Create new feature
df['Avg_Price_Per_Unit'] = df['Revenue'] / df['Units_Sold']

print("\nDataset after Feature Engineering:")
print(df.head())

# ==============================
# 4. Descriptive Statistics
# ==============================
print("\nOverall Statistics:")
print(df.describe())

print("\nGrouped Statistics by Region:")
group_stats = df.groupby('Region')[['Units_Sold', 'Revenue']].agg(['mean', 'median', 'std'])
print(group_stats)

# ==============================
# 5. Visualization - Bar Chart
# ==============================
avg_units = df.groupby('Region')['Units_Sold'].mean()

plt.figure()
avg_units.plot(kind='bar')
plt.title('Average Units Sold by Region')
plt.xlabel('Region')
plt.ylabel('Average Units Sold')
plt.show()

# ==============================
# 6. Visualization - Line Plot
# ==============================
monthly_revenue = df.groupby('Month')['Revenue'].sum()

plt.figure()
monthly_revenue.plot(kind='line')
plt.title('Total Revenue Trend Over 24 Months')
plt.xlabel('Month')
plt.ylabel('Total Revenue')
plt.show()

# ==============================
# 7. Simple Insight Prints
# ==============================
best_region = avg_units.idxmax()
print(f"\nRegion with Highest Average Sales: {best_region}")

max_revenue_month = monthly_revenue.idxmax()
print(f"Month with Highest Revenue: {max_revenue_month.date()}")